name = "PythagoreanTriples"
uuid = "cf5fe419-f069-44d7-b983-50e7569e004e"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]